Development
DariusDangi/fwf-api-poc-performer pull request #1
Opened 2024-08-14 08:26 UTC by DariusDangi

Ready for first code review.

2024-08-14 10:49 UTC, RobertFWF commented on DataLayer/DetermineAnimalType.xaml
Coloana de interes pentru "Animal" poate fi in Config

2024-08-14 10:49 UTC, RobertFWF commented on Exceptions_Screenshots/ExceptionScreenshot_240814.104822.png
Sterge scrennshot-urile

2024-08-14 10:50 UTC, RobertFWF commented on Framework/CloseAllApplications.xaml
Nefolosit

2024-08-14 10:50 UTC, RobertFWF commented on Framework/GetTransactionData.xaml
io_dt_TransactionData nefolosit deci il poti sterge de peste tot

2024-08-14 10:51 UTC, RobertFWF commented on Framework/InitAllApplications.xaml
Sheet-ul in Config

2024-08-14 10:51 UTC, RobertFWF commented on Framework/KillAllProcesses.xaml
Nefolosit

2024-08-14 10:55 UTC, RobertFWF commented on Framework/SetTransactionStatus.xaml
Statusul la SE e hardcoded, pune-l cu in_SystemException.Message
Nu folosesti CloseAllApplication deci poti sa il stergi si din proiect si de peste tot unde este folosit, la fel ca celelalte workflow-uri nefolosite.

La Write Status pune coloanele de interes si sheet-ul in Config 

Verifica numele activitatilor default

2024-08-14 10:58 UTC, RobertFWF commented on Main.xaml
In EndProcess ai activitatea de Send Output Report care se poate pune intr-un workflow separat tot in ServiceLayer

2024-08-14 11:02 UTC, RobertFWF commented on ServiceLayer/CallAnimalAPI.xaml
Dupa fiecare call de API adauga un if sa verifici statusul, daca nu a avut succes api-ul nu are rost sa continue workflow-ul
![image](https://github.com/user-attachments/assets/24d82d94-b781-43c6-9fa5-8b4efe9dc24f)

Endpoint-urile la API-uri in Config

2024-08-14 11:03 UTC, RobertFWF commented on ServiceLayer/SendEmailImageAttachment.xaml
Adresa la care trimiti sa fie in Config

2024-08-14 11:04 UTC, RobertFWF reviewed
First Code Review

2024-08-20 11:17 UTC, FlorinBarsan requested changes
just a few changes left, implement them please and request a re-review

2024-08-20 11:17 UTC, FlorinBarsan commented on Framework/GetTransactionData.xaml
remove variables that have no use (transaction fields) from the whole project

2024-08-20 11:17 UTC, FlorinBarsan commented on .codedworkflows/ConnectionsFactory.cs
delete that test.txt file from the project

2024-08-20 11:24 UTC, DariusDangi commented on Framework/GetTransactionData.xaml
Removed the variables/arguments transactionField1 and transactionField2 from the whole project

2024-08-20 11:24 UTC, DariusDangi commented on .codedworkflows/ConnectionsFactory.cs
deleted the test.txt file from project

2024-08-20 11:28 UTC, FlorinBarsan approved these changes
good job!

2024-08-20 11:28 UTC, merged